[package]
name = "objectkv"
version = "0.1.0"
edition = "2021"

[dependencies]
aws-config = { version = "1.5.4", features = ["behavior-version-latest"] }
aws-sdk-s3 = "1.42.0"
serde = "1.0.204"
tokio = { version = "1.38.1", features = ["full"] }
